name: namoz_najotdir
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-226.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animate_do: ^2.1.0
  carousel_slider: ^4.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  dio: ^4.0.4
  shared_preferences: ^2.0.12
  intl: ^0.17.0
  loading_animation_widget: ^1.0.0+3
  flutter_alarm_clock: ^0.0.2
  flutter_qiblah: ^2.0.2
  geolocator: ^7.7.1
  flutter_svg: ^1.0.3
  google_maps_flutter: ^2.1.1
  flutter_local_notifications: ^9.2.0
  timezone: ^0.8.0
  animated_card: ^2.0.0
  fluttertoast: ^8.0.8
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.3
  provider: ^6.0.2
  url_launcher: ^6.0.20
  alert_dialog: ^1.0.1 
  flutter_exit_app: ^1.0.5
  flutter_share: ^2.0.0
  audio_video_progress_bar: ^0.11.0
  just_audio: ^0.9.29
  just_audio_background: ^0.0.1-beta.7
  audio_session: ^0.1.10
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  path_provider: ^2.0.11
  workmanager: ^0.5.0
  
dev_dependencies:
  hive_generator: 
  build_runner: 
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/namoz_gif/
    - assets/tahorat_gif/
    - assets/images/compass.svg
    - assets/images/compas1.svg
  fonts:
    - family: Fonts
      fonts:
        - asset: assets/font/fonts.ttf
    - family: Balo
      fonts:
        - asset: assets/font/balo.ttf
    - family: Courgette
      fonts:
        - asset: assets/font/courgette.ttf